### ISSUE TITLE
The asset "mosaico/translations-en.js" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by ohaddahan** [camertron/mosaico-rails#6]
After clicking `New` in the `emails` view inside `https://github.com/ohaddahan/mosaico-fresh` I'm getting the error above. (`https://mosaico-fresh.herokuapp.com/emails`)
Only in production (using Heroku).

I have a feeling it's due to namespacing + compiled assets renaming.

**Comment by camertron** [comment]
Hey @ohaddahan, this was related to a bug in generated-assets. I published a new version last night, so you should be able to run `bundle update generated-assets` to fix the issue :)

**Comment by ohaddahan** [comment]
> 2019-02-12T23:09:01.036746+00:00 app[web.1]: ! Unable to load application: NoMethodError: undefined method `application' for Rake:Module
> 2019-02-12T23:09:01.036876+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
> 2019-02-12T23:09:01.036929+00:00 app[web.1]: NoMethodError: undefined method `application' for Rake:Module
> 2019-02-12T23:09:01.036932+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/manifest.rb:65:in `should_apply?'
> 2019-02-12T23:09:01.036934+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/manifest.rb:34:in `apply!'
> 2019-02-12T23:09:01.036935+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/railtie.rb:12:in `block in <class:Railtie>'
> 2019-02-12T23:09:01.036937+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
> 2019-02-12T23:09:01.036938+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
> 2019-02-12T23:09:01.036940+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
> 2019-02-12T23:09:01.036949+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
> 2019-02-12T23:09:01.036951+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
> 2019-02-12T23:09:01.036952+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
> 2019-02-12T23:09:01.036953+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
> 2019-02-12T23:09:01.036954+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
> 2019-02-12T23:09:01.036956+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
> 2019-02-12T23:09:01.036957+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
> 2019-02-12T23:09:01.036958+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
> 2019-02-12T23:09:01.036959+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
> 2019-02-12T23:09:01.036960+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
> 2019-02-12T23:09:01.036961+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
> 2019-02-12T23:09:01.036963+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
> 2019-02-12T23:09:01.036964+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
> 2019-02-12T23:09:01.036965+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
> 2019-02-12T23:09:01.036966+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
> 2019-02-12T23:09:01.036967+00:00 app[web.1]: /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
> 2019-02-12T23:09:01.036968+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
> 2019-02-12T23:09:01.036969+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
> 2019-02-12T23:09:01.036970+00:00 app[web.1]: /app/config/environment.rb:5:in `<top (required)>'
> 2019-02-12T23:09:01.036972+00:00 app[web.1]: config.ru:3:in `require_relative'
> 2019-02-12T23:09:01.036973+00:00 app[web.1]: config.ru:3:in `block in <main>'
> 2019-02-12T23:09:01.036974+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
> 2019-02-12T23:09:01.036975+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
> 2019-02-12T23:09:01.036977+00:00 app[web.1]: config.ru:in `new'
> 2019-02-12T23:09:01.036978+00:00 app[web.1]: config.ru:in `<main>'
> 2019-02-12T23:09:01.036979+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
> 2019-02-12T23:09:01.036980+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
> 2019-02-12T23:09:01.036981+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
> 2019-02-12T23:09:01.036982+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
> 2019-02-12T23:09:01.036983+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
> 2019-02-12T23:09:01.036984+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
> 2019-02-12T23:09:01.036985+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
> 2019-02-12T23:09:01.036986+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
> 2019-02-12T23:09:01.036987+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
> 2019-02-12T23:09:01.036988+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
> 2019-02-12T23:09:01.036989+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
> 2019-02-12T23:09:01.036990+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
> 2019-02-12T23:09:01.150481+00:00 heroku[web.1]: Process exited with status 1
> 2019-02-12T23:09:01.185481+00:00 heroku[web.1]: State changed from starting to crashed
> 2019-02-12T23:09:00.693606+00:00 app[unfollow_3.1]: [heroku-exec] Starting
> 2019-02-12T23:09:03.098442+00:00 heroku[follow_2.1]: Starting process with command `QUEUES=follow,mailers   WORKER_NAME=follow_2   rake jobs:work`
> 2019-02-12T23:09:03.881477+00:00 heroku[follow_2.1]: State changed from starting to up
> 2019-02-12T23:09:03.686627+00:00 heroku[unfollow_2.1]: Starting process with command `QUEUES=unfollow,mailers WORKER_NAME=unfollow_2 rake jobs:work`
> 2019-02-12T23:09:04.472222+00:00 heroku[unfollow_2.1]: State changed from starting to up
> 2019-02-12T23:09:04.416799+00:00 app[follow_3.1]: console_debug :: NOT Inside Rails::Console
> 2019-02-12T23:09:04.419130+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:4: warning: already initialized constant LUMINATI_PROXY_SHARED_IP_IL
> 2019-02-12T23:09:04.419133+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:4: warning: previous definition of LUMINATI_PROXY_SHARED_IP_IL was here
> 2019-02-12T23:09:04.419134+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:5: warning: already initialized constant LUMINATI_PROXY_SHARED_IP_US
> 2019-02-12T23:09:04.419140+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:5: warning: previous definition of LUMINATI_PROXY_SHARED_IP_US was here
> 2019-02-12T23:09:04.419142+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:6: warning: already initialized constant DEFAULT_IL_PROXY
> 2019-02-12T23:09:04.419144+00:00 app[follow_3.1]: /app/config/initializers/my_proxy.rb:6: warning: previous definition of DEFAULT_IL_PROXY was here
> 2019-02-12T23:09:04.712499+00:00 app[follow_1.1]: Delayed::Backend::ActiveRecord::Job Load (2.0ms)  UPDATE "delayed_jobs" SET locked_at = '2019-02-12 23:09:04.709737', locked_by = 'host:a885e213-b8f9-4d90-8200-3d6271c483b0 pid:4' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2019-02-12 23:09:04.709024' AND (locked_at IS NULL OR locked_at < '2019-02-12 22:59:04.709050') OR locked_by = 'host:a885e213-b8f9-4d90-8200-3d6271c483b0 pid:4') AND failed_at IS NULL) AND "delayed_jobs"."queue" IN ('follow', 'mailers') ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
> 2019-02-12T23:09:04.802994+00:00 app[follow_3.1]: [Worker(host:6dd75a7e-3079-4e3d-af99-ee35171f2eba pid:4)] Starting job worker
> 2019-02-12T23:09:04.803068+00:00 app[follow_3.1]: 2019-02-12T23:09:04+0000: [Worker(host:6dd75a7e-3079-4e3d-af99-ee35171f2eba pid:4)] Starting job worker
> 2019-02-12T23:09:04.858557+00:00 app[follow_3.1]: Delayed::Backend::ActiveRecord::Job Load (2.7ms)  UPDATE "delayed_jobs" SET locked_at = '2019-02-12 23:09:04.852943', locked_by = 'host:6dd75a7e-3079-4e3d-af99-ee35171f2eba pid:4' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2019-02-12 23:09:04.803119' AND (locked_at IS NULL OR locked_at < '2019-02-12 22:59:04.803141') OR locked_by = 'host:6dd75a7e-3079-4e3d-af99-ee35171f2eba pid:4') AND failed_at IS NULL) AND "delayed_jobs"."queue" IN ('follow', 'mailers') ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
> 2019-02-12T23:09:06.989341+00:00 app[follow_2.1]: [heroku-exec] Starting
> 2019-02-12T23:09:07.864995+00:00 app[unfollow_2.1]: [heroku-exec] Starting
>

**Comment by ohaddahan** [comment]
```
 ! Unable to load application: NoMethodError: undefined method `application' for Rake:Module
 bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
 NoMethodError: undefined method `application' for Rake:Module
 /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/manifest.rb:65:in `should_apply?'
 /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/manifest.rb:34:in `apply!'
 /app/vendor/bundle/ruby/2.6.0/gems/generated-assets-2.1.3/lib/generated-assets/railtie.rb:12:in `block in <class:Railtie>'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
 /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
 /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
 /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
 /app/config/environment.rb:5:in `<top (required)>'
 config.ru:3:in `require_relative'
 config.ru:3:in `block in <main>'
 /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
 /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
 config.ru:in `new'
 config.ru:in `<main>'
 /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
 /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
 /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
 /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
 /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
 /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
 Process exited with status 1
 State changed from starting to crashed


```

**Comment by ohaddahan** [comment]
@camertron this caused new issue.
Seems like other gems had a similar issue https://github.com/westfieldlabs/apivore/issues/75

**Comment by camertron** [comment]
@ohaddahan Oh man... obviously I never actually tried to deploy this to a real production environment! I tried late last week and found all sorts of little bugs and issues, mostly related to assets. I had forgotten for example that Mosaico embeds TinyMCE, which comes with its own set of assets that mosaico-rails wasn't handling.

That said, I was able to address all the issues and actually got the thing deployed to Heroku: https://mosaico-camertron.herokuapp.com/emails

To that end, new versions of the mosaico and generated-assets gems, v1.1.0 and 2.1.4 respectively, are now available. You should be able to run `bundle update --source mosaico` and deploy to Heroku :)

**Comment by ohaddahan** [comment]
Thanks, works now :)
